### ISSUE TITLE
Wheels for CPython 3.10+ on PyPI

### ISSUE THREAD

**Issue by aurivus-ph** [celiagg/celiagg#106]
On [PyPI](https://pypi.org/project/celiagg/), wheels for CPython 3.6-3.9 are available.

It would be nice if wheels for 3.10 and 3.11 were released, to allow for easy installation.

**Comment by jwiggins** [comment]
I agree. I'll see what I can do.

**Comment by jwiggins** [comment]
[2.1.3](https://pypi.org/project/celiagg/2.1.3/#files) now available

**Comment by aurivus-ph** [comment]
Thanks!
