### ISSUE TITLE
Error installing in Linux Mint 64bit

### ISSUE THREAD

**Issue by marco-mf3** [celiagg/celiagg#15]
Hi,
thanks for your interesting work.
When I try to install in linux, I have this:

`pip install celiagg
Collecting celiagg
  Using cached celiagg-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-S2efXP/celiagg/setup.py", line 54, in <module>
        with open('README.rst', 'r') as fp:
    IOError: [Errno 2] No such file or directory: 'README.rst'

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-S2efXP/celiagg/
`

**Comment by jwiggins** [comment]
Doh! Thanks for the bug report. I'll have 0.1.3 out soon.
