### ISSUE TITLE
font.width(text) produce different results before and after drawing

### ISSUE THREAD

**Issue by vsvasya** [celiagg/celiagg#62]
Hello!

Thanks for the great module!
All works perfectly except one thing: measured text width depends on transform which we used in previous draw_text call.

Demo:
```python
import celiagg as agg

canvas = agg.CanvasRGB24(np.ones((200,200,3), dtype=np.uint8))
font = agg.Font('Helvetica-Regular.ttf', 40.0, agg.FontCacheType.RasterFontCache)
state = agg.GraphicsState(drawing_mode=agg.DrawingMode.DrawStroke, line_width=2)
paint = agg.SolidPaint(0.0, 0.0, 0.0)

canvas.clear(1.0, 1.0, 1.0)

angle = 0.75
pos = (100, 100)
text = "123"

transform = agg.Transform()
transform.translate(pos[0] - 0.5*font.width(text), 0.5*font.height)
transform.rotate(angle)

print(font.width(text)) # produce 67.0 as expected

# if we apply any draw_text with transform then all changes
canvas.draw_text(text, font, transform, state, stroke=paint)

print(font.width(text)) # 49.023154214546
# We got 49 but expected 67.0.
# So the next text drawing with different transform based on text width
# will be misaligned
```

So we get all kinds of strangeness in result, like swapping two function calls `draw_object1(); draw_object2()` produce different picture.

I check out module code, but seems cause may be hidden in agg. Although Font class apllies transform on itself before each drawing, font.string_width method and glyphiterator looks independent of it at surface.

**Comment by jwiggins** [comment]
This is quite a strange bug. You're right that nothing looks wrong in `GlyphIterator`. Here's what I do see in `draw_text`:
https://github.com/celiagg/celiagg/blob/1c0efd97e5b1cec97d453f998a0ff5b7f398e9f4/celiagg/ndarray_canvas.hxx#L289-L297

`font.transform(mtx)` calls `m_font_engine.transform(transform)`; `m_font_engine` is a `agg::font_engine_freetype_int32` instance (unless you're using Windows). My guess is that modifying the transform of the font engine causes it to give you a different result when measuring text.

Try this: Call `canvas.draw_text('', font, agg.Transform(), state, stroke=paint)` after drawing your text and then see what result you get from `font.width(text)`. I would hope that you get the correct answer. Granted, that's a workaround that's probably terrible for performance. I think the correct thing to do is to reset the font engine transform at the end of each `draw_text` call...
