### ISSUE TITLE
Fonts can't load all fonts from .ttc files with FreeType engine

### ISSUE THREAD

**Issue by corranwebster** [celiagg/celiagg#63]
Sometimes fonts are found in .ttc archive files which contain multiple related fonts.  In these cases you need to pass the index of the font in the file to free type as well as the file, I think here:

https://github.com/celiagg/celiagg/blob/1af9287ea193ca3e355526c4481cf6e34fa57bae/celiagg/font.cpp#L60

But that means that the Celiagg `Font` needs to have the index information available (and assume 0 if not provided).

**Comment by jwiggins** [comment]
Sure enough, that's exactly where we can do this. The [Freetype docs](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_open_face) have more detail. (`face_index` is what that `0` gets passed as)
